Assignment 2

Date: 23/07/24

1. What is Robustscaler? \
    Ans: Robust Scaler uses the median and IQR(Inter Quartile Range) to scale the data hence the scaled data is robust to outliers.

2. Apply RobustScaler() on X = [[ 1., -2.,  2.],[ -2.,  1.,  3.],[ 4.,  1., -2.]]

In [4]:
from sklearn.preprocessing import RobustScaler
x = [[ 1, -2,  2],[ -2,  1,  3],[ 4,  1, -2]]
scaler = RobustScaler()
scaler.fit(x).transform(x)

array([[ 0. , -2. ,  0. ],
       [-1. ,  0. ,  0.4],
       [ 1. ,  0. , -1.6]])

3. Apply StandardScaler and RobustScaler() on [[5],[10],[12],[14],[18],[23] [49]]. Theoritically calculate  whether the calculated result  is matching with code result

In [8]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler

x = [[5],[10],[12],[14],[18],[23],[49]]

std_scaler = StandardScaler().fit(x).transform(x)
print("Standard Scaler")
print(std_scaler)

rob_scaler = RobustScaler().fit(x).transform(x)
print("Robust Scaler")
print(rob_scaler)

Standard Scaler
[[-1.01920247]
 [-0.64761823]
 [-0.49898454]
 [-0.35035085]
 [-0.05308346]
 [ 0.31850077]
 [ 2.25073878]]
Robust Scaler
[[-0.94736842]
 [-0.42105263]
 [-0.21052632]
 [ 0.        ]
 [ 0.42105263]
 [ 0.94736842]
 [ 3.68421053]]


In [15]:
#Theoretical Calculation
import numpy as np
x = np.array([[5],[10],[12],[14],[18],[23],[49]])

#Standard Scaler
mean = np.mean(x)
print("Mean: ", mean)

std = np.std(x)
print("Standard Deviation: ", std)

standard_scaled_data = (x - mean)/std
print("Standard Scaled Data: \n", standard_scaled_data)

#Robust Scaler
median = np.median(x)
print("Median: ", median)

q1 = np.percentile(x, 25)
q3 = np.percentile(x, 75)
iqr = q3 - q1
print("IQR: ", iqr)

robust_scaled_data = (x - median)/iqr
print("Robust Scaled Data: \n", robust_scaled_data)

Mean:  18.714285714285715
Standard Deviation:  13.455899244933278
Standard Scaled Data: 
 [[-1.01920247]
 [-0.64761823]
 [-0.49898454]
 [-0.35035085]
 [-0.05308346]
 [ 0.31850077]
 [ 2.25073878]]
Median:  14.0
IQR:  9.5
Robust Scaled Data: 
 [[-0.94736842]
 [-0.42105263]
 [-0.21052632]
 [ 0.        ]
 [ 0.42105263]
 [ 0.94736842]
 [ 3.68421053]]


4. Apply StandardScaler() on [[ 1., -1.,  2.],[ 2.,  0.,  0.],[ 0.,  1., -1.]]

In [9]:
x = [[ 1, -1,  2],[ 2,  0,  0],[ 0,  1, -1]]
scaler = StandardScaler()
scaler.fit(x).transform(x)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

5. Apply MaxAbsScaler() on X = [[ 1., -1.,  2.],[ 2.,  0.,  0.],[ 0.,  1., -1.]]

In [13]:
from sklearn.preprocessing import MaxAbsScaler
x = [[ 1, -1,  2],[ 2,  0,  0],[ 0,  1, -1]]
scaler = MaxAbsScaler()
scaler.fit(x).transform(x)

array([[ 0.5, -1. ,  1. ],
       [ 1. ,  0. ,  0. ],
       [ 0. ,  1. , -0.5]])

6. Apply OneHotEncoder() on [['Male', 1], ['Female', 3], ['Female', 2]]

In [16]:
from sklearn.preprocessing import OneHotEncoder
x = [['Male', 1], ['Female', 3], ['Female', 2]]
encoder = OneHotEncoder()
encoder.fit(x).transform(x).toarray()

array([[0., 1., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0.]])

7. Apply MultiLabelBinarizer() on [{'sci-fi', 'thriller'}, {'comedy'}]. Apply classes_ method.

In [19]:
from sklearn.preprocessing import MultiLabelBinarizer
x = [{'sci-fi', 'thriller'}, {'comedy'}]
encoder = MultiLabelBinarizer()
encoder.fit(x).classes_

array(['comedy', 'sci-fi', 'thriller'], dtype=object)